### ISSUE TITLE
the package source url was broken

### ISSUE THREAD

**Issue by yurenchen000** [kihamo/openwrt#1]
the `whois_5.1.1.tar.xz` from debian package pool
http://ftp.debian.org/debian/pool/main/w/whois
was broken,

I found it from ubuntu package pool
http://archive.ubuntu.com/ubuntu/pool/main/w/whois/
http://archive.ubuntu.com/ubuntu/pool/main/w/whois/whois_5.1.1.tar.xz

Files: 
 aa4561134a03e22e2d759748ca676a97 73832 whois_5.1.1.tar.xz

**Comment by kihamo** [comment]
@yurenchen000 thanks for your report. I think update to latest version will be better. I updated to version 5.2.15. If you need version 5.1.1, I can make a separate package, but still it's better to update.

**Comment by yurenchen000** [comment]
@kihamo 
thanks, 
I modified the `PKG_SOURCE_URL`  myself.

post url here just for someone else.
